# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "squid233's Blog"
weight = 2
[en.params]
sidebar.subtitle = "Everyone is a lonely star"
comments.giscus.lang = "en"

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "squid233的博客"
weight = 1
[zh-cn.params]
sidebar.subtitle = "千里之行，始于足下。"
comments.giscus.lang = "zh-CN"
