title: squid233's Blog
author:
  name: squid233
description: This is squid233's blog.
url: "https://squid233.github.io/"

theme: minima

disqus:
  shortname: squid233
show_excerpts: true
minima:
  header_pages:
    - about.md
    - posts.md
    - series-make-a-game.md
